### PR TITLE
updated index.ts as mentioned in the issue #1

### PR DESCRIPTION
**Pull request by ashutosh7i**
completed this task-

Our Bot Has a new command /hacktoberfest , we need to add the repositories added there so that anyone can see all the available repositories provided by GDSC-NSEC.

### CODE REVIEW

**Review by unownone — CHANGES_REQUESTED** [review]
The Repos contain all the repos though we only want repos that have `hacktoberfest` tag in them.

**Comment by ashutosh7i** [comment]
> The Repos contain all the repos though we only want repos that have `hacktoberfest` tag in them.

oh, sorry i was unaware of that, because it was not told earlier, 
I am fixing  that right now,
apart from that, is everything fine?

**Comment by unownone** [comment]
@ashutosh7i Everything else looks great!

**Review by ashutosh7i — COMMENTED** [review]
i have done the changes , please merge the pull request

**Review by unownone — APPROVED** [review]
Seems Great!

**Comment by ashutosh7i** [comment]
Thank you for merging my pull request, it was a nice time contribution for your project

**Pull request merged**
